SELECT
    C.CAR_ID,
    C.CAR_TYPE,
    ROUND(C.DAILY_FEE * (100 - DP.DISCOUNT_RATE) / 100 * 30) AS FEE
FROM CAR_RENTAL_COMPANY_CAR AS C
JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY AS H
ON C.CAR_ID = H.CAR_ID
JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS DP
ON C.CAR_TYPE = DP.CAR_TYPE
WHERE C.CAR_ID NOT IN (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS H
    WHERE '2022-11-01' <= H.END_DATE
    AND H.START_DATE <= '2022-11-30'
)
AND DP.DURATION_TYPE = '30일 이상'
AND C.CAR_TYPE IN ('세단', 'SUV')
GROUP BY C.CAR_ID
HAVING FEE BETWEEN 500000 AND 2000000
ORDER BY 3 DESC, CAR_TYPE ASC, CAR_ID DESC