SELECT 
    YEAR(SALES_DATE) AS YEAR, 
    MONTH(SALES_DATE) AS MONTH, 
    UI.GENDER, 
    COUNT(DISTINCT OS.USER_ID) AS USERS
FROM ONLINE_SALE AS OS
JOIN USER_INFO AS UI
ON UI.USER_ID = OS.USER_ID AND UI.GENDER IS NOT NULL
GROUP BY YEAR(SALES_DATE), MONTH(SALES_DATE), GENDER
ORDER BY 1, 2, 3;