SELECT J.CATEGORY, SUM(J.SALES) AS TOTAL_SALES
FROM (
SELECT BS.BOOK_ID, SUM(SALES) AS SALES, B.CATEGORY
FROM BOOK_SALES AS BS
JOIN BOOK AS B
ON B.BOOK_ID = BS.BOOK_ID
WHERE MONTH(BS.SALES_DATE) = '1'
GROUP BY BS.BOOK_ID
    ) AS J
GROUP BY J.CATEGORY
ORDER BY 1;